import React from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
  Box,
  Alert,
  Divider,
} from '@mui/material';
import WarningAmberIcon from '@mui/icons-material/WarningAmber';

interface TermsOfServiceModalProps {
  open: boolean;
  onClose: () => void;
}

const TermsOfServiceModal: React.FC<TermsOfServiceModalProps> = ({ open, onClose }) => {
  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
      scroll="paper"
    >
      <DialogTitle>
        <Typography variant="h5" component="div" fontWeight="bold">
          Terms of Service
        </Typography>
        <Typography variant="caption" color="text.secondary">
          Last Updated: February 15, 2026
        </Typography>
      </DialogTitle>

      <DialogContent dividers>
        {/* Critical Disclaimers */}
        <Alert severity="warning" icon={<WarningAmberIcon />} sx={{ mb: 3 }}>
          <Typography variant="subtitle2" fontWeight="bold" gutterBottom>
            IMPORTANT: Educational Project Notice
          </Typography>
          <Typography variant="body2">
            TripMeBuddy is a <strong>learning and upskilling project</strong> and is <strong>NOT a refined commercial product</strong>. 
            This platform is provided for educational and demonstration purposes only. It is not intended for commercial use 
            or professional travel planning services.
          </Typography>
        </Alert>

        <Alert severity="error" sx={{ mb: 3 }}>
          <Typography variant="subtitle2" fontWeight="bold" gutterBottom>
            AI-Generated Content Warning
          </Typography>
          <Typography variant="body2">
            This service leverages artificial intelligence and produces <strong>unsupervised AI-generated results</strong> which may 
            accidentally contain dangerous, hazardous, inaccurate, or inappropriate recommendations. While we implement AI safety 
            best practices, data protection measures, and security protocols, <strong>users must independently verify all travel 
            recommendations, prices, and safety information</strong> before making any booking or travel decisions.
          </Typography>
        </Alert>

        {/* Standard Terms */}
        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            1. Acceptance of Terms
          </Typography>
          <Typography variant="body2" paragraph>
            By accessing and using TripMeBuddy ("Service", "Platform"), you accept and agree to be bound by these Terms of Service. 
            If you do not agree to these terms, please do not use this service.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            2. Nature of Service
          </Typography>
          <Typography variant="body2" paragraph>
            TripMeBuddy is an AI-powered travel planning platform that provides trip recommendations, flight and hotel search 
            capabilities, and itinerary generation through artificial intelligence technology.
          </Typography>
          <Typography variant="body2" paragraph>
            <strong>Educational Purpose:</strong> This platform was developed as a learning project to demonstrate AI integration, 
            cloud architecture, and full-stack development practices. It is not a commercial travel agency or booking platform.
          </Typography>
          <Typography variant="body2" paragraph>
            <strong>Third-Party Data:</strong> Travel data is sourced from third-party APIs (Amadeus, Google Gemini AI). We do not 
            guarantee accuracy, completeness, or real-time availability of this information.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            3. AI-Generated Content and Limitations
          </Typography>
          <Typography variant="body2" paragraph>
            <strong>No Warranty on AI Recommendations:</strong> All trip recommendations, itineraries, and travel suggestions are 
            generated by artificial intelligence and are provided "as-is" without warranty of any kind. AI models may produce:
          </Typography>
          <ul style={{ marginLeft: '20px', marginTop: '8px', marginBottom: '8px' }}>
            <li><Typography variant="body2">Outdated or inaccurate information</Typography></li>
            <li><Typography variant="body2">Unsafe or inappropriate recommendations</Typography></li>
            <li><Typography variant="body2">Pricing discrepancies</Typography></li>
            <li><Typography variant="body2">Factual errors or hallucinations</Typography></li>
            <li><Typography variant="body2">Biased or culturally insensitive content</Typography></li>
          </ul>
          <Typography variant="body2" paragraph>
            <strong>User Responsibility:</strong> You are solely responsible for verifying all information, prices, safety conditions, 
            visa requirements, health advisories, and travel restrictions before making any travel plans or bookings.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            4. User Responsibilities
          </Typography>
          <Typography variant="body2" paragraph>
            You agree to:
          </Typography>
          <ul style={{ marginLeft: '20px', marginTop: '8px', marginBottom: '8px' }}>
            <li><Typography variant="body2">Provide accurate information when using the service</Typography></li>
            <li><Typography variant="body2">Use the service for lawful purposes only</Typography></li>
            <li><Typography variant="body2">Not attempt to compromise the security or integrity of the platform</Typography></li>
            <li><Typography variant="body2">Not use automated systems to access the service without permission</Typography></li>
            <li><Typography variant="body2">Independently verify all travel recommendations before acting on them</Typography></li>
          </ul>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            5. No Booking or Transaction Services
          </Typography>
          <Typography variant="body2" paragraph>
            TripMeBuddy <strong>does not provide booking, reservation, or transaction services</strong>. We do not sell flights, 
            hotels, or any travel services. The platform provides informational travel planning recommendations only. Any bookings 
            or purchases must be made directly with travel providers.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            6. Data Security and Privacy
          </Typography>
          <Typography variant="body2" paragraph>
            We implement industry-standard security practices including:
          </Typography>
          <ul style={{ marginLeft: '20px', marginTop: '8px', marginBottom: '8px' }}>
            <li><Typography variant="body2">OAuth 2.0 authentication via Keycloak</Typography></li>
            <li><Typography variant="body2">Encrypted data transmission (HTTPS/TLS)</Typography></li>
            <li><Typography variant="body2">AWS cloud security best practices</Typography></li>
            <li><Typography variant="body2">GDPR-aligned data handling principles</Typography></li>
          </ul>
          <Typography variant="body2" paragraph>
            However, as an educational project, we cannot guarantee enterprise-level security. See our Privacy Policy for details 
            on data collection and usage.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            7. Limitation of Liability
          </Typography>
          <Typography variant="body2" paragraph>
            <strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</strong>
          </Typography>
          <Typography variant="body2" paragraph>
            TripMeBuddy and its creators shall not be liable for any direct, indirect, incidental, consequential, or special damages 
            arising from:
          </Typography>
          <ul style={{ marginLeft: '20px', marginTop: '8px', marginBottom: '8px' }}>
            <li><Typography variant="body2">Use or inability to use the service</Typography></li>
            <li><Typography variant="body2">Inaccurate or dangerous AI-generated recommendations</Typography></li>
            <li><Typography variant="body2">Reliance on information provided by the platform</Typography></li>
            <li><Typography variant="body2">Financial losses from travel decisions based on our recommendations</Typography></li>
            <li><Typography variant="body2">Personal injury, property damage, or other harm during travel</Typography></li>
            <li><Typography variant="body2">Data breaches or unauthorized access to your information</Typography></li>
          </ul>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            8. Indemnification
          </Typography>
          <Typography variant="body2" paragraph>
            You agree to indemnify and hold harmless TripMeBuddy, its creators, and contributors from any claims, damages, or 
            expenses arising from your use of the service or violation of these terms.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            9. Service Availability
          </Typography>
          <Typography variant="body2" paragraph>
            The service is provided on an "as available" basis. We do not guarantee continuous, uninterrupted, or secure access. 
            The platform may be modified, suspended, or discontinued at any time without notice.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            10. Third-Party Services
          </Typography>
          <Typography variant="body2" paragraph>
            This platform integrates with third-party services (Amadeus API, Google Gemini AI, Keycloak). Your use of these 
            services is subject to their respective terms and privacy policies. We are not responsible for third-party services.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            11. Intellectual Property
          </Typography>
          <Typography variant="body2" paragraph>
            The platform source code, design, and original content are provided under open-source principles for educational purposes. 
            Third-party data and AI-generated content may be subject to separate licenses.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            12. Changes to Terms
          </Typography>
          <Typography variant="body2" paragraph>
            We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes 
            acceptance of the modified terms.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            13. Governing Law
          </Typography>
          <Typography variant="body2" paragraph>
            These terms are governed by applicable laws without regard to conflict of law principles. As an educational project, 
            disputes should be resolved amicably and informally when possible.
          </Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            14. Contact Information
          </Typography>
          <Typography variant="body2" paragraph>
            For questions about these terms, please contact the project maintainers through the GitHub repository or project 
            documentation.
          </Typography>
        </Box>

        <Alert severity="info" sx={{ mt: 3 }}>
          <Typography variant="body2">
            <strong>Remember:</strong> This is an educational demonstration platform. Always verify travel information with 
            official sources, licensed travel agents, and relevant authorities before making any travel decisions.
          </Typography>
        </Alert>
      </DialogContent>

      <DialogActions>
        <Button onClick={onClose} variant="contained" color="primary">
          Close
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default TermsOfServiceModal;
